### ISSUE TITLE
vfat sort

### ISSUE THREAD

**Issue by ghost** [mk-fg/fgtk#1]
I am trying to find or write a command line program for Windows that will sort
FAT32 drives

http://softwarerecs.stackexchange.com/q/19575

Is this possible using `vfat_shuffler` as a starting point? I could use a push in the
right direction.

**Comment by mk-fg** [comment]
Yeah, I think your case looks very similar to the one I wrote that script for, where "by the order they were added to the drive" was essentially due to "order of fat dentries".

---

Steve Barnes' answer on the stack-exchange link above mentions that your player might also use date/time ordering, which indeed would also produce same sequence of entries, and should be easier to change (no need for custom fs "driver").

I'd suggest testing if that's the case first by either using command-line tool like "touch" or doing it from whatever scripting language (e.g. python), if you're familiar with any.

It might be a bad idea to test it with whatever audio editing software, as it probably doesn't "change" files in-place, but creates a new (changed) file instead, then renames it to the original name, to avoid
having neither original nor new file if something breaks, so it might not actually change modification time of the file (or modifies original one at all, for that matter).

If that's the case (date/time ordering), "vfat_shuffler" script won't help, but much simpler script can, essentially something like this:

```
import os, random, time
time_now = int(time.time())
for file_name in os.listdir(whatever_dir):
  os.utime(
    os.path.join(whatever_dir, file_name),
    random.randint(time_now - 2**20, time_now) )
```

That'd set date/time values for each file in "whatever_dir" (variable in the code above) to random time between 2^20 seconds (~1mil) in the past and now, effectively shuffling the entries by that parameter.

Again, would only help if it matters to the player-device, of course, which seem rather unlikely though.

---

And if that simple way doesn't work, and it's indeed the "order of fat dentries" case for your player as well, what "vfat_shuffler" does should work for you...

But!

I don't think script itself would work, as I don't have windows here, never tried - or even thought of trying it out - there, and have no idea how you'd get access to raw device contents under that os.

On linux/bsd/*nix there's a "special files" (device nodes), like /dev/sdb1 ("sd" is a prefix assigned to libata devices by linux/udev, "b" is alphabetic-order sequential "device letter" and "1" is a partition number on /dev/sdb, as detected by linux kernel), which correspond to "block device" and behave mostly same as a regular file - i.e. you can read/write bytes from whatever place there.

And if you want to access filesystem on that device, you'd mount it (command/syscall name) to some vfs path, e.g. with "mount" command: `mount -t vfat /dev/sdb1 my-sd-card`

Once fs is mounted like that, if you make changes to underlying blocks directly, filesystem code will derp, probably give whatever errors, and might even corrupt the data, as it assumes exclusive access and doesn't expect stuff changing between when it reads data into fs cache and then writes it back.

So vfat_shuffler can't (well, shouldn't) really be used on already-mounted filesystems.

And in windows, as far as I know:
- All devices/filesystems are always mounted automatically (and you get "drive letter", like "D:" for each fs), but can be unmounted via "safely remove device" systray button.
- There's no /dev/ filesystem/entries, like in unix world, so there's no "path to a file with filesystem in it" equivalent.
  
  "vfat_shuffler" has required "Path to FAT32 device" argument, which definitely won't work with windows for reason above, as far as I know, at least.
- Existing software I've seen for that OS, e.g. [win32diskimager](http://sourceforge.net/projects/win32diskimager/), uses "drive letters" to somehow reach underlying device from which fs corresponding to these was mounted.
  
  Then I guess it unmounts the fs and does whatever it wants on the device directly - this is definitely missing in vfat_shuffler, but is probably some simple code, given how generic (and easy) the operation seem to be, maybe in win32 python module (if we're talking about cPython, no doubt it should be trivial in .NET langs)...

Currently script just grabs "device file" path passed on command line (e.g. /dev/sdb1 on linux) and does `with open(opts.dev, 'r' if opts.list else 'r+') as src: ...all-the-stuff-with-src...`, so I'd say just find a way to "open()" device on windows and the rest of the code should work fine with it.

`open('D:', 'r+')` might work, I guess, but it seem highly unlikely and kinda wrong, as you don't need filesystem (which D: represents), but rather the underlying device/partition itself.

---

Sorry for a bit of a long-winded and rambling answer, hope it helps clear things out, and do check date/time ordering first - if by some weird chance it works like that, 5-liner script above would be an easy and efficient solution.

**Comment by mk-fg** [comment]
Actually, I assumed that you have windows from stack exchange thread, but it doesn't say that anywhere in your question.

If you have linux, osx or such, script should "just work", I guess.

**Comment by ghost** [comment]
@mk-fg it is Windows, and Steve Barnes is mistaken, my flash drive like all is sorted by dentries, not date/time.

**Comment by mk-fg** [comment]
Oh well, Steve Barnes seem to be mistaken only in the first section of his reply though ("Date/Time Ordering"), "vfat_shuffler" indeed parses dentries and writes them back in random order (or just lists, with --list option), but to get it to work on windows you need to make that `open(device)` bit work there (which again, probably as easy as it is on linux, I just don't know how due to my lack of xp with that os).

**Comment by ghost** [comment]
@mk-fg my question is not about how to get it to work with Windows, my question is about how to get it to sort rather than shuffle

**Comment by mk-fg** [comment]
Oh, heh, guess I missed that bit as well, apologies.

There's this line in the script:

```
for struct, data in path.shuffled_structs(group_dirs=opts.group_dirs):
```

Which calls to this func:

```
def shuffled_structs( self,
    group_dirs='first',
    order_func=random.shuffle,
    order_dirs=lambda dirs: sorted(dirs, key=op.attrgetter('dirEntry.name_long')) ):
```

Replace that line above with:

```
for struct, data in path.shuffled_structs(group_dirs=opts.group_dirs, order_func=ft.partial(sorted, key=op.attrgetter('name')):
```

So that `random.shuffle` becomes `sorted(..., key=op.attrgetter('name')`, essentially, and you should have all files ordered neatly by name.

Mind the other ordering key wrt dirs though, which can be controlled from cli:

```
-g GROUP_DIRS, --group-dirs GROUP_DIRS
                    Group and sort directories at the beginning/end of the
                    file entries. Possible values: no, first, last.
                    Default: first
```

**Comment by ghost** [comment]
Another question, does your script do recursion?

**Comment by mk-fg** [comment]
It's aware of the nested dirs to be able to descend into the one you want to shuffle, as per required options:

```
positional arguments:
  dev                   Path to FAT32 device.
  path                  Directory to shuffle. Must start from /, example: /some/my/dir
```

So it's aware of recursion in that sense, but doesn't try go into subdirs of that dir, and sort all their contents as well, if that's what you mean.

It can be easily changed to do that though, just add a loop (near the end of the script) under that initial descend (after `path = path[k]` loop) and run the code below for each "path" (shuffling each shouldn't affect others later, as it's done in-place).

**Comment by mk-fg** [comment]
Ermm... shuffling -> sorting in your case, of course.
