### ISSUE TITLE
ssh-keyparse base64

### ISSUE THREAD

**Issue by Quezler** [mk-fg/fgtk#12]
When i base_64 decode the seed to store it as binary in the database it often defaults to nothing.

```
            base64_decode($base64string),
            $base64string,
```
results in
`["","5_DbkBn6IhczM4r-rlIIzrkoLaiNYUchVviGnNqNuf0="]`

About 30% of the time the first half stays empty, otherwise it works just as intended.

And when you paste the base64 string into other converters (e.g. https://cryptii.com/base64/binary) it does not interpret it as well.

What am i missing here?

**Comment by mk-fg** [comment]
Script is using [urlsafe_b64encode](https://docs.python.org/3/library/base64.html#base64.urlsafe_b64encode), which `substitutes - instead of + and _ instead of /`.
These symbols don't conflict, obviously, so you can decode either by replacing `"-" -> "+" and "_" -> "/"` then using standard decode.
I'm always using urlsafe version, so don't think I've even considered that it might be non-obvious or non-decodable in other places... will add a note on it at least, I guess, thanks for reporting.

**Comment by Quezler** [comment]
Ah, in hindsight it was obvious that it was urlsafe, i just didn't expect to see it since the function that encodes it is called `data = base64.b64encode(data)`, perhaps rename it to e.g. `data = urlsafebase64.b64encode(data)` or `data = base64.urlsafeb64encode(data)`?

**Comment by mk-fg** [comment]
It's just not the one used for output, which is encoded here (with `base64.urlsafe_b64encode(res)`):
https://github.com/mk-fg/fgtk/blob/75664e6/ssh-keyparse#L403

**Comment by mk-fg** [comment]
One you refer to - `b64encode()` - is the one I've added recently for encoding ssh key after --patch-key, should only be used there, and uses standard encoding as that's what openssh expects.

**Comment by mk-fg** [comment]
Have updated script to use same b64encode() everywhere, just with urlsafe=True opt for output, though it's probably a moot point by now :)
