### ISSUE TITLE
Interoperability with OpenSSL

### ISSUE THREAD

**Issue by jchevali** [mk-fg/fgtk#15]
This is a request for an enhancement.

I wonder if you could add an option similar to `--public`, perhaps call it `--private`, to produce the OpenSSL private key (whether in base64 or hex form) for convenience.

Notice that I'm making a distinction here between the private key for OpenSSH, which OpenSSL would call 'seed', and OpenSSL's own key they call 'private', derived from seed.

The reason is that right now it is convenient to isolate a private key to inject later into other OpenSSH key files, but injecting the said key into a private key file generated by OpenSSL requires deriving the private key from the hash, and it is not convenient to do by hand, or I don't know a ready-made tool to do it.

The closest I know is NewKeyFromSeed() in [this Go implementation](https://github.com/golang/crypto/raw/master/ed25519/ed25519.go).

The RFC 8032 has an Appendix A with a detailed Python 3.2 implementation but that only implements sign, not NewKeyFromSeed (even though within sign it might get calculated).

If we could output the private key with `--private`, the next step could be that `-d --private` inserts the key into a OpenSSL-generated private key file instead of OpenSSH.

That'd help bridging the gap between OpenSSH and OpenSSL which is not always easy to cross.

**Comment by mk-fg** [comment]
> private key file generated by OpenSSL requires deriving the private key from the hash

I'm not a cryptographer and didn't even bother to read RFC 8032, but since you've pointed out that there's python example in there, checked it out, and this bit:

    def keygen(self,privkey):
      #If no private key data is given, generate random.
      if privkey is None: privkey=os.urandom(self.b//8)
      #Expand key.
      khash=self.H(privkey,None,None)
      a=from_le(self.__clamp(khash[:self.b//8]))
      #Return the key pair (public key is A=Enc(aB).
      return privkey,(self.B*a).encode()

Looks exactly like how ed25519 keys are generated in OpenSSH and ssh-keyparse script.
I.e. `privkey=os.urandom(...)` is the actual "seed" value (that ssh-keyparse prints), and the rest is what ed25519_pubkey_from_seed() does, including the hashing.

So if I understand this correctly, only thing is missing is parsing OpenSSL X.509/PEM/DER certs to either get seed value out of them, or update key in there (and all the hashes) from such seed value.

Given how complex these certs are compared to OpenSSH formats, it'd almost certainly be easier to grab some lib like cryptography.io and either use or patch it to parse/update such files, and not re-implement it in ad-hoc fashion like with ssh formats.

Doubt I'll get around to doing that anytime soon though, or likely ever, as don't think I ever needed to manage keys in TLS certs, using them pretty much exclusively for http/smtp and such, where they're very interchangeable (can be generated and signed via LE in seconds), plus EdDSA isn't even supported in web-tls infra (basically LE) yet.
It's probably more useful for stuff like OpenVPN where PEM files are for client auth, but I'm unlikely to ever need these, and tool for them should probably be made/maintained by someone who actually uses it.

So if you need such functionality, I'd suggest looking at cryptography.io, as mentioned - code there might already support such use-case (or to parse/insert raw expanded key blob, at least), or should be easy to adapt if it doesn't.
Also iirc it was mentioned in one of the issues of this repo that it also has vastly more optimized code for expanding that "seed" into proper key than ssh-keyparse, which uses math code straight from reference djb implementation.

**Comment by mk-fg** [comment]
> I'd suggest looking at cryptography.io

Oh, also, maybe doesn't need to be said, but pretty sure it can be done via OpenSSL itself, as it tends to expose all kinds of internals.
And even if it has some opaque structs for keys, these should be easy to dereference and tweak, esp. compared to building whole cert thing around it.

**Comment by mk-fg** [comment]
> So if I understand this correctly, only thing is missing is parsing OpenSSL X.509/PEM/DER certs to either get seed value out of them, or update key in there (and all the hashes) from such seed value.

It randomly occured to me that I was confusing how public/private keys are stored with OpenSSL above.

Private keys don't get wrapped into certs, and cert can be generated from private key rather easily via openssl scripts or any tools, so there isn't much point patching them there (esp. as it'd invalidate any signatures).

Guess ssh-keygen might not support exporting to OpenSSL private key format yet, hence this issue.

Still don't care much about these myself, and easiest solution is probably the same - use some crypto lib or wrapper that'd support saving Ed25519 keys in OpenSSL private key format (which can be OpenSSL itself of course).
