### ISSUE TITLE
vfat_shuffler: Cannot re-mount into /media/$user/$autoname

### ISSUE THREAD

**Issue by cweiske** [mk-fg/fgtk#19]
Debian stable (and Ubuntu 18.x and 20.x) automatically mount USB flash drives under `/media/$username/$driveLabel`.

vfat_shuffler unmounts it, and the system automatically removes the folder. Then the vfat_shuffler wants to re-mount it, and that fails because the folder is gone:
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./bin/vfat_shuffler.py", line 667, in <module>
    if __name__ == '__main__': sys.exit(main())
  File "./bin/vfat_shuffler.py", line 665, in main
    if res.returncode: res.check_returncode()
  File "/usr/lib/python3.8/subprocess.py", line 444, in check_returncode
    raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command '['mount', '/dev/sdb1', '/media/cweiske/music']' returned non-zero exit status 32.
```

**Comment by mk-fg** [comment]
Never used any kind of auto-mount systems myself, so never really bumped into this issue.
Don't think I can do much about it though, just don't use script in that re-mount mode.

Workarounds should be:

- Use device paths instead of mountpoints, e.g.: `vfat_shuffler /dev/sdX1 /some/dir --list`
- Use -u/--umount option: `vfat_shuffler -u /media/somedev/somedir --list`

Note that when using device nodes with any kind of ops that change stuff, filesystem should probably be unmounted manually first, as otherwise any later changes (or ones not yet flushed to device) on that mountpoint might corrupt the filesystem, as linux won't expect stuff changing under it like that.
Operations like --list should be safe though.
